version: '3'

services:
  node-web-app:
    build: ./prodenv
    container_name: node-web-app
    volumes:
      - ./prodenv:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 4660:4660
